### ISSUE TITLE
Dark Mode 対応が不完全？

### ISSUE THREAD

**Issue by euxn23** [moekidev/timesy#1]
OS の設定が Dark Mode の場合に、投稿内容の背景のみが黒くなってしまう
![IMG_7462](https://github.com/moekidev/timesy/assets/5271091/def8f94f-aac0-4937-8b84-4f9bc8df1a03)

**Comment by moekidev** [comment]
なるほどー。ライブラリが勝手にダークモードに対応してるっぽいですね

**Comment by moekidev** [comment]
せっかくなんでダークモードに対応してみます。
